name: dogs_dashboard
description: Deliveristo Flutter Coding Challenge.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  bloc_test: ^9.1.5
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.8
  get_it: ^7.6.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.3.2
  intl: ^0.18.1
  marquee: ^2.2.3
  shimmer: ^3.0.0
  sizer: ^2.0.15

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/gen/images/
    - assets/gen/icons/

  fonts:
    - family: Trap
      fonts:
        - asset: assets/fonts/Trap/Trap-Black 900.otf
          weight: 900
        - asset: assets/fonts/Trap/Trap-ExtraBold 800.otf
          weight: 800
        - asset: assets/fonts/Trap/Trap-Bold 700.otf
          weight: 700
        - asset: assets/fonts/Trap/Trap-SemiBold 600.otf
          weight: 600
        - asset: assets/fonts/Trap/Trap-Medium 500.otf
          weight: 500
        - asset: assets/fonts/Trap/Trap-Regular 400.otf
          weight: 400
        - asset: assets/fonts/Trap/Trap-Light 300.otf
          weight: 300

    - family: IBM Plex Sans Arabic
      fonts:
        - asset: assets/fonts/IBM Plex Sans Arabic/IBMPlexSansArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBM Plex Sans Arabic/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBM Plex Sans Arabic/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBM Plex Sans Arabic/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBM Plex Sans Arabic/IBMPlexSansArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/IBM Plex Sans Arabic/IBMPlexSansArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBM Plex Sans Arabic/IBMPlexSansArabic-Thin.ttf
          weight: 100

flutter_intl:
  enabled: true

flutter_assets:
  assets_path: assets/gen/
  output_path: lib/core/utils/
  filename: assets.dart
  field_prefix: null

flutter_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true
  min_sdk_android: 21
